[build]
  base = "apps/frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://rpm-13-production.up.railway.app"

[[redirects]]
  from = "/portfolio/*"
  to = "/portfolio/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200