#!/bin/bash
# Quick deploy script for backend

echo "🚀 Quick Backend Deploy Script"
echo "=============================="
echo ""
echo "Option 1: Deploy to Render.com (Recommended)"
echo "---------------------------------------------"
echo "1. Go to https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. New + → Web Service"
echo "4. Connect repo: RPM-1.3"
echo "5. Settings:"
echo "   - Name: rpm-backend"
echo "   - Root Directory: apps/backend"
echo "   - Build: pip install -r requirements.txt"
echo "   - Start: uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo "6. Click Create (wait 5-10 min)"
echo "7. Copy URL and update Streamlit"
echo ""
echo "Option 2: Use Railway.app"
echo "-------------------------"
echo "1. Go to https://railway.app"
echo "2. New Project → Deploy from GitHub"
echo "3. Select RPM-1.3 repo"
echo "4. Deploy (automatic)"
echo "5. Generate domain"
echo ""
echo "Option 3: Temporary with localtunnel"
echo "------------------------------------"
echo "Running localtunnel now..."
lt --port 8000