name: Deploy Streamlit App

on:
  push:
    branches:
      - main
    paths:
      - 'apps/streamlit-frontend/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        working-directory: apps/streamlit-frontend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run tests
        working-directory: apps/streamlit-frontend
        run: |
          pytest tests/ -v --cov=lib --cov=components
      
      - name: Check code quality
        working-directory: apps/streamlit-frontend
        run: |
          pip install black flake8
          black --check .
          flake8 . --max-line-length=120

  deploy-streamlit-cloud:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Streamlit Cloud
        env:
          STREAMLIT_API_TOKEN: ${{ secrets.STREAMLIT_API_TOKEN }}
        run: |
          # Streamlit Cloud deployment via API
          echo "Deploying to Streamlit Cloud..."
          # Add deployment script here

  deploy-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: apps/streamlit-frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/rpm-streamlit:latest
            ${{ secrets.DOCKER_REGISTRY }}/rpm-streamlit:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/rpm-streamlit:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/rpm-streamlit:buildcache,mode=max